apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage
  namespace: jobmgmt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-storage
  template:
    metadata:
      labels:
        app: file-storage
    spec:
      containers:
        - name: file-storage
          image: ghcr.io/samaresh-16/file-storage:latest
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: file-storage
  namespace: jobmgmt
spec:
  type: NodePort
  selector:
    app: file-storage
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
