apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: jobmgmt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: ghcr.io/samaresh-16/job-service:fc5e82de053763ec66822078c0c41dd69437afa8
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: jobmgmt
spec:
  type: NodePort
  selector:
    app: job-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30085
