apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: jobmgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: ghcr.io/samaresh-16/job-service:latest
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: jobmgmt
spec:
  type: NodePort
  selector:
    app: job-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30085
